version: 2.1

jobs:
  # Job to say hello
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  # Job to run SonarQube analysis
  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli  # Use the Sonar Scanner image directly
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Run Sonar Scanner"
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="." \
            -Dsonar.java.binaries=build  # If using Java, specify the binaries path

  # Job to run Postman tests
  postman-tests:
    docker:
      - image: cimg/node:18  # Use a Node.js image for Newman
    steps:
      - checkout
      - run:
          name: "Install Newman"
          command: npm install -g newman
      - run:
          name: "Run Postman Tests"
          command: newman run server/tests/APDS_PART2.postman_collection.json --reporters cli,html --reporter-html-export ./newman/report.html

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
      - postman-tests 
