version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli  # Use the Sonar Scanner image directly
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "npm install"
      - run:
          name: "Run tests"
          command: "npm run test"
      - run:
          name: "Run Sonar Scanner"
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="src" \
              -Dsonar.exclusions="**/node_modules/**,**/*.test.js,**/*.spec.js" \
              -Dsonar.javascript.lcov.reportPaths="coverage/lcov.info"
workflows:
  version: 2
  test-and-analyze:
    jobs:
      - say-hello
      - sonarqube:
          requires:
            - run-tests
